openapi: 3.0.3
info:
  version: v1
  title: FarmStall API
  description: |-
    An API for writing reviews about your favourite ( or worst ) farm stalls.

    ![Picture of produce](produce-banner.jpg)

    ---

    # Auth

    With a *User* account ( see [POST Users](#Users/post_users) ) you can then get a **UserToken** from the [POST /tokens](#Users/post_tokens) operation. <br/>
    The **UserToken** token must be set in the `Authorization` header when an operation requires any user based authorization.

    # Reviews
    Reviews are the heart of this API. <br/>
    Registered **Users** and anonymous users can both write reviews based on their experience at farm stalls. <br/>
    Both positive and negative reviews are encouraged to better the experience of others.

    When creating a review, if the `Authorization` is set with the **UserToken** then the review will be created as that user. <br/>
    Otherwise the review will be created anonymously.

    #### Details

    Reviews have simple messages that can relate how the experience was. <br/>
    And UserId references the author of the review. Can be anonymous.

    Each review comes with a rating of between one and five stars inclusive. <br/>

    - One star being the worst experience
    - Five stars being the best


    ### Example Reviews

    |                  Message | Rating | User        |
    |-------------------------|:-------|-------------|
    | A wonderful time!        | ![5 stars](rating-5.png)      | Bob McNally |
    | An awful place           | ![1 star](rating-1.png)      | _Anonymous_  |
    | A totally average place. | ![3 stars](rating-3.png)      | Jane Fair   |

    ---

  contact:
    name: Josh Ponelat
    email: jponelat+daso@gmail.com
    url: https://farmstall.designapis.com
  license:
    url: https://www.apache.org/licenses/LICENSE-2.0
    name: Apache 2.0
externalDocs:
  url: https://farmstall.designapis.com
  description: Hosted docs
servers:
- url: https://farmstall.designapis.com/v1
paths:
  /reviews:
    get:
      description: Get a list of reviews
      parameters:
      - name: maxRating
        in: query
        schema:
          type: number
      responses:
        '200':
          description: A bunch of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    rating:
                      type: integer
                      minimum: 1
                      maximum: 5
                    message:
                      type: string
                      example: An awesome time for the whole family.
                    uuid:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                      example: 3b5b1707-b82c-4b1d-9078-157053902525
                    userId:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                      nullable: true
                      example: 3b5b1707-b82c-4b1d-9078-157053902525
    post:
      description: Create a new Review
      security: 
      - MyUserToken: []
      requestBody:
        description: A new Review
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: An awesome time for the whole family.
                rating:
                  type: integer
                  example: 5
                  minimum: 1
                  maximum: 5
      responses:
        '201':
          description: Successfully created a new Review
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An awesome time for the whole family.
                  rating:
                    type: integer
                    example: 5
                    minimum: 1
                    maximum: 5
                  userId:
                    type: string
                    nullable: true
                    pattern: '^[0-9a-fA-F\-]{36}$'
                    example: 3b5b1707-b82c-4b1d-9078-157053902525
                  uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
                    example: 3b5b1707-b82c-4b1d-9078-157053902525
  /reviews/{reviewId}:
    get:
      description: Get a single review
      parameters:
      - name: reviewId
        in: path
        required: true
        schema:
          type: string
          description: The review's ID
          example: 3b5b1707-b82c-4b1d-9078-157053902525
          minLength: 36
          maxLength: 36
          pattern: '[a-zA-Z0-9-]+'
      responses:
        '200':
          description: A single review
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An awesome time for the whole family.
                  rating:
                    type: integer
                    example: 5
                    minimum: 1
                    maximum: 5
                  userId:
                    minLength: 36
                    maxLength: 36
                    pattern: '^[a-zA-Z0-9-]+$'
                    nullable: true
                    example: 3b5b1707-b82c-4b1d-9078-157053902525
                  uuid:
                    minLength: 36
                    maxLength: 36
                    pattern: '^[a-zA-Z0-9-]+$'
                    example: 3b5b1707-b82c-4b1d-9078-157053902525
  /users:
    post:
      description: Create a new user
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: ponelat
                password:
                  type: string
                  format: password
                fullName:
                  type: string
                  example: Josh Ponelat
      responses:
        '201':
          description: Successfully created a new user
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: ponelat
                  uuid:
                    type: string
                    example: f7f680a8-d111-421f-b6b3-493ebf905078
  /tokens:
    post: 
      description: Create a new token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: ponelat
                password:
                  type: string
                  format: password
          
      responses:
        '201':
          description: Create a new token for gaining authenticated access to resources
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    
components:
  securitySchemes:
    MyUserToken:
      type: apiKey
      in: header
      name: Authorization
